const ACTION_UPLOAD_ADD_FILE = 'ACTION_UPLOAD_ADD_FILE';

//Home
const ACTION_HOME_ADD_ITEMS = 'ACTION_HOME_ADD_ITEMS';
const ACTION_HOME_BEGIN_LOADING = 'ACTION_HOME_BEGIN_LOADING';
const ACTION_HOME_LOADING_FINISH = 'ACTION_HOME_LOADING_FINISH';
const ACTION_HOME_NO_MORE = 'ACTION_HOME_NO_MORE';

//P2P share
const ACTION_P2P_SHARE_ADD_TORRENT = 'ACTION_P2P_SHARE_ADD_TORRENT';
const ACTION_P2P_SHARE_UPDATE_CLIENT_INFO = 'ACTION_P2P_SHARE_UPDATE_CLIENT_INFO';
const ACTION_P2P_SHARE_REMOVE_TORRENT = 'ACTION_P2P_SHARE_REMOVE_TORRENT';
const ACTION_P2P_SHARE_CHANGE_STATE = 'ACTION_P2P_SHARE_CHANGE_STATE';
const ACTION_P2P_SHARE_STATE_NORMAL = 'ACTION_P2P_SHARE_STATE_NORMAL';
const ACTION_P2P_SHARE_STATE_ADD_UPLOAD_ING = 'ACTION_P2P_SHARE_STATE_ADD_UPLOAD_ING';
const ACTION_P2P_SHARE_STATE_ADD_DOWNLOAD_ING = 'ACTION_P2P_SHARE_STATE_ADD_DOWNLOAD_ING';

export {
    ACTION_UPLOAD_ADD_FILE,
    ACTION_P2P_SHARE_ADD_TORRENT,
    ACTION_P2P_SHARE_UPDATE_CLIENT_INFO,
    ACTION_P2P_SHARE_REMOVE_TORRENT,
    ACTION_P2P_SHARE_CHANGE_STATE,
    ACTION_P2P_SHARE_STATE_ADD_DOWNLOAD_ING,
    ACTION_P2P_SHARE_STATE_ADD_UPLOAD_ING,
    ACTION_P2P_SHARE_STATE_NORMAL,
    ACTION_HOME_ADD_ITEMS,
    ACTION_HOME_BEGIN_LOADING,
    ACTION_HOME_LOADING_FINISH,
    ACTION_HOME_NO_MORE,
}